# Generated by Django 5.0.2 on 2024-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragraphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
