# Generated by Django 5.0.2 on 2024-07-12 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragraphs', '0002_alter_paragraph_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paragraphs.paragraph')),
            ],
        ),
    ]
